In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('netflix.csv')

In [4]:
data.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   object
 1   type          8790 non-null   object
 2   title         8790 non-null   object
 3   director      8790 non-null   object
 4   country       8790 non-null   object
 5   date_added    8790 non-null   object
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   object
 8   duration      8790 non-null   object
 9   listed_in     8790 non-null   object
dtypes: int64(1), object(9)
memory usage: 686.8+ KB

In [ ]:
# Tasks:
# Delete redundant columns
# Rename columns
# Drop duplicates
# Remove NaN values
# Optimize dataset

In [8]:
data.drop(columns="rating", inplace=True)

In [9]:
data.head()

,show_id,type,title,director,country,date_added,release_year,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,125 min,"Dramas, Independent Movies, International Movies"

In [11]:
data.columns

Index(['show_id', 'type', 'title', 'director', 'country', 'date_added',
       'release_year', 'duration', 'listed_in'],
      dtype='object')

In [ ]:
# Tasks:
# Rename columns
# Drop duplicates
# Remove NaN values
# Optimize dataset

In [29]:
data.columns = data.columns.str.capitalize()

In [30]:
data.head()

,Show_id,Type,Title,Director,Country,Date_added,Release_year,Duration,Listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,125 min,"Dramas, Independent Movies, International Movies"

In [31]:
data.columns

Index(['Show_id', 'Type', 'Title', 'Director', 'Country', 'Date_added',
       'Release_year', 'Duration', 'Listed_in'],
      dtype='object')

In [ ]:
# Tasks:
# Drop duplicates
# Remove NaN values
# Optimize dataset

In [34]:
data.duplicated().sum()

np.int64(0)

In [ ]:
# For cleaning duplicates (where applicable):

data.drop_duplicates(inplace=True)

In [ ]:
# Tasks:
# Remove NaN values
# Optimize dataset

In [38]:
data.isna()

,Show_id,Type,Title,Director,Country,Date_added,Release_year,Duration,Listed_in
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
8785,False,False,False,False,False,False,False,False,False
8786,False,False,False,False,False,False,False,False,False
8787,False,False,False,False,False,False,False,False,False
8788,False,False,False,False,False,False,False,False,False
8789,False,False,False,False,False,False,False,False,False

In [39]:
data.isna().sum()

Show_id         0
Type            0
Title           0
Director        0
Country         0
Date_added      0
Release_year    0
Duration        0
Listed_in       0
dtype: int64

In [41]:
# For removing NaN values (where applicable):

data.dropna(inplace=True)

In [42]:
data.head()

,Show_id,Type,Title,Director,Country,Date_added,Release_year,Duration,Listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,125 min,"Dramas, Independent Movies, International Movies"

In [43]:
data["Show_id"].unique()

array(['s1', 's3', 's6', ..., 's8801', 's8784', 's8786'],
      shape=(8790,), dtype=object)

In [44]:
data["Show_id"] = data["Show_id"].str.replace("s", "")

In [45]:
data["Show_id"].unique()

array(['1', '3', '6', ..., '8801', '8784', '8786'],
      shape=(8790,), dtype=object)

In [48]:
type(data["Show_id"][0])

str

In [49]:
data["Show_id"] = data["Show_id"].astype(int)

In [50]:
data["Date_added"].unique()

array(['9/25/2021', '9/24/2021', '9/22/2021', ..., '5/22/2016',
       '9/11/2019', '4/1/2014'], shape=(1713,), dtype=object)

In [51]:
data["Date_added"] = data["Date_added"].str.replace("/", "-")

In [52]:
data["Date_added"].unique()

array(['9-25-2021', '9-24-2021', '9-22-2021', ..., '5-22-2016',
       '9-11-2019', '4-1-2014'], shape=(1713,), dtype=object)

In [53]:
data

,Show_id,Type,Title,Director,Country,Date_added,Release_year,Duration,Listed_in
0,1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9-25-2021,2020,90 min,Documentaries
1,3,TV Show,Ganglands,Julien Leclercq,France,9-24-2021,2021,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,6,TV Show,Midnight Mass,Mike Flanagan,United States,9-24-2021,2021,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9-22-2021,2021,91 min,"Children & Family Movies, Comedies"
4,8,Movie,Sankofa,Haile Gerima,United States,9-24-2021,1993,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...
8785,8797,TV Show,Yunus Emre,Not Given,Turkey,1-17-2017,2016,2 Seasons,"International TV Shows, TV Dramas"
8786,8798,TV Show,Zak Storm,Not Given,United States,9-13-2018,2016,3 Seasons,Kids' TV
8787,8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12-15-2016,2012,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,8784,TV Show,Yoko,Not Given,Pakistan,6-23-2018,2016,1 Season,Kids' TV
8789,8786,TV Show,YOM,Not Given,Pakistan,6-7-2018,2016,1 Season,Kids' TV

In [55]:
data.to_csv('Cleaned_Dataset_CSV.csv', index=False)

In [2]:
# Import to Excel instead:
 
# data.to_excel('Cleaned_Dataset_Excel.xlsx', index=False)

In [3]:
pip freeze > requirements.txt

Note: you may need to restart the kernel to use updated packages.